package com.intuit.spring.pulsar.client.exceptions

import kotlin.reflect.KClass

/**
 * Annotation for classes that hold handlers for exceptions generated by Pulsar Consumers/Producers
 */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.RUNTIME)
annotation class PulsarExceptionHandlerClass

/**
 * Annotation for properties that are handlers for exceptions generated by Pulsar Consumers
 */
@Target(AnnotationTarget.PROPERTY, AnnotationTarget.FIELD)
@Retention(AnnotationRetention.RUNTIME)
annotation class PulsarConsumerExceptionHandlerFunction(vararg val exceptions: KClass<out Exception>)

/**
 * Annotation for properties that are handlers for exceptions generated by Pulsar Producers
 */
@Target(AnnotationTarget.PROPERTY, AnnotationTarget.FIELD)
@Retention(AnnotationRetention.RUNTIME)
annotation class PulsarProducerExceptionHandlerFunction(vararg val exceptions: KClass<out Exception>)

/**
 * Annotation for properties that are handlers for exceptions generated by Pulsar Readers
 */
@Target(AnnotationTarget.PROPERTY, AnnotationTarget.FIELD)
@Retention(AnnotationRetention.RUNTIME)
annotation class PulsarReaderExceptionHandlerFunction(vararg val exceptions: KClass<out Exception>)
