server:
  port: 8081

pulsar:
  client:
    serviceUrl: pulsar://localhost:6650
    tls:
      tlsAllowInsecureConnection: true
      tlsHostnameVerificationEnable: false
    auth:
      userName: admin
      password: apachepulsar
  sample01:
    topic:
      name: java-sample-topic01
    subscription:
      name: java-sample-sub01
      type: Key_Shared
    consumer:
      count: 1
  sample02:
    topic:
      name: java-sample-topic02
    subscription:
      name: java-sample-sub02
      type: Key_Shared
    consumer:
      count: 1
