name: Build and Test

on:
 push:
    branches: [ master ]
 pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install gpg secret key
      run: cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
    - name: Build project with Maven
      run: mvn -Dgpg.passphrase=${{ secrets.OSSRH_GPG_PASSPHRASE }} -pl spring-pulsar-test --batch-mode clean install
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start pulsar cluster
        run: docker run -d  -p 6650:6650  -p 8080:8080 -h pulsar --name pulsar apachepulsar/pulsar:latest bin/pulsar standalone
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build project with Maven
        run: mvn --batch-mode clean test -f spring-pulsar-test/pom.xml

