name: Publish to staging repo
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Show github context
        run: echo $GITHUB_CONTEXT
      - name: Install gpg secret key
        run: cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: mvn -Darguments="-Dgpg.passphrase=${{ secrets.OSSRH_GPG_PASSPHRASE}}" -DautoVersionSubmodules=true  release:clean release:prepare release:perform
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
